// Build script that generates config.js from environment variables
const fs = require('fs');
const path = require('path');

const token = process.env.GITHUB_TOKEN;
if (!token) {
    console.warn('Warning: GITHUB_TOKEN not found in environment. Project preview will use public repos only.');
}

const configContent = `// This file is generated by build-config.js
// DO NOT edit directly or commit to repository
window.GITHUB_TOKEN = ${token ? `'${token}'` : 'null'};
`;

fs.writeFileSync(path.join(__dirname, 'config.js'), configContent);
console.log('Generated config.js' + (token ? ' with token' : ' without token'));
